analysis_task:
  description: >
    Analyze "cat_patients.json" to find patterns in drug effectiveness, 
    side effects, and treatment outcomes. Identify success rates and risk factors.
  expected_output: >
    A structured dataset showing drug success rates, side effect frequencies, 
    and breed-specific responses.
  agent: medical_researcher
  output_file: "raw_analysis.json"  # Save findings as JSON

reporting_task:
  description: >
    Summarize the analysis into a readable report. Include insights into 
    drug performance, side effects, and breed-specific recommendations.
  expected_output: >
    A markdown report with medication performance details, side effect trends, 
    and treatment insights.
  agent: treatment_analyst
  output_file: "veterinary_analysis_report.md"

data_organization_task:
  description: >
    Organize and structure the analyzed data for future use. Ensure all findings 
    are categorized and stored properly.
  expected_output: >
    A structured JSON dataset with treatment metrics, drug details, and 
    breed-specific insights.
  agent: data_coordinator
  output_file: "organized_data.json"
